# Jekyll Configuration

url: http://localhost:4000 #XXX
title: Site Name #XXX
description: Tag line #XXX
author: A. U. Thor #XXX
email: a.u.thor@example.com #XXX
analytics_id: #Google Analytics ID : UA-xxx-xxx  

auto: false
lsi: false
pygments: false
server_port: 4000
markdown: maruku

maruku:
  use_tex: false
  use_divs: false
  png_dir: img/tex
  png_url: /img/tex


